In [1]:
filename = 'rankings/1_to_50.txt'

In [2]:
f = open(filename, 'r')

In [3]:
def index_after_find(main_str, sub_str):
    i = main_str.find(sub_str)
    if i == -1: return i
    return i + len(sub_str)

In [4]:
def format_country(country):
    if country == 'United States':
        return 'USA'
    elif 'China' in country:
        return 'China'
    elif 'Hong Kong' in country:
        return 'Hong Kong'
    elif country == 'United Kingdom':
        return 'UK'
    else:
        return country

In [5]:
def remove_bracket(uni):
    if uni[-1] == ')':
        idx = uni.rindex('(')
        uni = uni[:idx].strip()
    return uni

In [6]:
rankings_dict = {}

In [7]:
def add_to_rankings(uni, country, rank):
    if country not in rankings_dict:
        rankings_dict[country] = {}
#         rankings_dict[country] = []

    rankings_dict[country][uni] = rank
#     rankings_dict[country].append((uni, rank))

In [8]:
for line in f:
    if len(line) < 10:
        rank = line.strip()
        if rank[0] == '=': rank = rank[1:]
        continue
    else:
        uni = line[:line.find(' Logo')].strip()
        uni = remove_bracket(uni)
        country = line[index_after_find(line, 'More'):].strip()
        country = format_country(country)
        
        add_to_rankings(uni, country, rank)

In [9]:
rankings_dict

{'USA': {'Massachusetts Institute of Technology': '1',
  'Stanford University': '2',
  'Carnegie Mellon University': '3',
  'University of California, Berkeley': '4',
  'Harvard University': '7',
  'Princeton University': '11',
  'University of California, Los Angeles': '15',
  'University of Washington': '18',
  'Columbia University': '19',
  'Cornell University': '19',
  'New York University': '19',
  'Georgia Institute of Technology': '27',
  'California Institute of Technology': '29',
  'University of Texas at Austin': '31',
  'University of Illinois at Urbana-Champaign': '33',
  'University of Pennsylvania': '35',
  'University of Southern California': '44',
  'Yale University': '46',
  'University of Chicago': '47',
  'University of Michigan-Ann Arbor': '48',
  'University of Maryland, College Park': '50'},
 'UK': {'University of Oxford': '5',
  'University of Cambridge': '6',
  'Imperial College London': '14',
  'UCL': '17',
  'The University of Edinburgh': '23'},
 'Switzerland': {'EPFL': '8',
  'ETH Zurich - Swiss Federal Institute of Technology': '9'},
 'Canada': {'University of Toronto': '10',
  'University of Waterloo': '24',
  'University of British Columbia': '25'},
 'Singapore': {'National University of Singapore': '12',
  'Nanyang Technological University, Singapore': '16'},
 'China': {'Tsinghua University': '13',
  'Peking University': '19',
  'Shanghai Jiao Tong University': '34'},
 'Hong Kong': {'The Hong Kong University of Science and Technology': '26',
  'The Chinese University of Hong Kong': '30',
  'The University of Hong Kong': '38'},
 'Japan': {'The University of Tokyo': '28'},
 'Australia': {'The University of Melbourne': '32',
  'The Australian National University': '41',
  'The University of Sydney': '42'},
 'South Korea': {'KAIST - Korea Advanced Institute of Science & Technology': '36',
  'Seoul National University': '48'},
 'Germany': {'Technical University of Munich': '36'},
 'France': {'Université PSL': '39'},
 'Italy': {'Politecnico di Milano': '40'},
 'Sweden': {'KTH Royal Institute of Technology': '43'},
 'Netherlands': {'University of Amsterdam': '45'}}

## Lower Ranks
Universities are not assigned individual ranks, but rather range ranks such as 51-100 and 101-150.
We assign the average rank to these institutions (e.g. rank 51-100 is recorded as rank 75)

In [10]:
filename = 'rankings/51-600.txt'

In [11]:
f = open(filename, 'r')

In [12]:
def format_rank(rank):
    sp = rank.split('-')
    if len(sp) < 2: return rank
    new_rank = str(int((int(sp[0]) + int(sp[1]) - 1)/2))
    return new_rank

In [13]:
for line in f:
    if len(line) < 10:
        rank = format_rank(line.strip())
        continue
    else:
        uni = line[:line.find(' Logo')].strip()
        uni = remove_bracket(uni)
        country = line[index_after_find(line, 'More'):].strip()
        country = format_country(country)
        
        add_to_rankings(uni, country, rank)

In [14]:
rankings_dict

{'USA': {'Massachusetts Institute of Technology': '1',
  'Stanford University': '2',
  'Carnegie Mellon University': '3',
  'University of California, Berkeley': '4',
  'Harvard University': '7',
  'Princeton University': '11',
  'University of California, Los Angeles': '15',
  'University of Washington': '18',
  'Columbia University': '19',
  'Cornell University': '19',
  'New York University': '19',
  'Georgia Institute of Technology': '27',
  'California Institute of Technology': '29',
  'University of Texas at Austin': '31',
  'University of Illinois at Urbana-Champaign': '33',
  'University of Pennsylvania': '35',
  'University of Southern California': '44',
  'Yale University': '46',
  'University of Chicago': '75',
  'University of Michigan-Ann Arbor': '48',
  'University of Maryland, College Park': '75',
  'Boston University': '75',
  'Duke University': '75',
  'Purdue University': '75',
  'University of Wisconsin-Madison': '75',
  'Brown University': '125',
  'Johns Hopkins University': '125',
  'Northwestern University': '125',
  'Pennsylvania State University': '125',
  'Rutgers University–New Brunswick': '125',
  'University of California, Irvine': '125',
  'University of Massachusetts Amherst': '125',
  'University of North Carolina, Chapel Hill': '125',
  'Arizona State University': '175',
  'Michigan State University': '175',
  'Northeastern University': '175',
  'The Ohio State University': '175',
  'Rice University': '175',
  'Stony Brook University, State University of New York': '175',
  'Texas A&M University': '175',
  'University of California, Santa Barbara': '175',
  'University of Illinois at Chicago': '175',
  'University of Pittsburgh': '175',
  'University of Virginia': '175',
  'Virginia Polytechnic Institute and State University': '175',
  'Indiana University Bloomington': '225',
  'The University of Arizona': '225',
  'University of California, Davis': '225',
  'University of Colorado Boulder': '225',
  'University of Florida': '225',
  'University of Minnesota Twin Cities': '225',
  'George Washington University': '275',
  'North Carolina State University': '275',
  'University of Notre Dame': '275',
  'University of Texas Dallas': '275',
  'Washington State University': '275',
  'Washington University in St. Louis': '275',
  'Dartmouth College': '325',
  'Florida State University': '325',
  'George Mason University': '325',
  'Illinois Institute of Technology': '325',
  'Syracuse University': '325',
  'University of Rochester': '325',
  'University of Utah': '325',
  'Vanderbilt University': '325',
  'Rensselaer Polytechnic Institute': '375',
  'University at Buffalo SUNY': '375',
  'University of California, Santa Cruz': '375',
  'University of Central Florida': '375',
  'University of Miami': '375',
  'University of South Florida': '375',
  'City University of New York': '425',
  'Georgetown University': '425',
  'Georgia State University': '425',
  'Iowa State University': '425',
  'University of California, Riverside': '425',
  'University of South Carolina': '425',
  'The University of Tennessee, Knoxville': '425',
  'Case Western Reserve University': '475',
  'William & Mary': '475',
  'Emory University': '475',
  'New Jersey Institute of Technology': '475',
  'The University of Georgia': '475',
  'Tufts University': '475',
  'University of Connecticut': '475',
  'University of Houston': '475',
  'University of Nebraska - Lincoln': '475',
  'University of Texas Arlington': '475',
  'Wayne State University': '475',
  'Brigham Young University': '525',
  'Clemson University': '525',
  'Colorado State University': '525',
  'Florida International University': '525',
  'Michigan Technological University': '525',
  'Oregon State University': '525',
  'Rutgers University–Newark': '525',
  'Temple University': '525',
  'The University of Alabama': '525',
  'University of Maryland, Baltimore County': '525',
  'University of New Mexico': '525',
  'University of Oregon': '525',
  'University of Texas at San Antonio': '525',
  'Worcester Polytechnic Institute': '525',
  'Texas Tech University': '575',
  'University of Kansas': '575',
  'University of Kentucky': '575',
  'University of Massachusetts Boston': '575',
  'University of Missouri, Columbia': '575'},
 'UK': {'University of Oxford': '5',
  'University of Cambridge': '6',
  'Imperial College London': '14',
  'UCL': '17',
  'The University of Edinburgh': '23',
  "King's College London": '75',
  'The University of Manchester': '75',
  'The London School of Economics and Political Science': '125',
  'The University of Warwick': '125',
  'University of Glasgow': '125',
  'University of Southampton': '125',
  'Lancaster University': '175',
  'Queen Mary University of London': '175',
  'The University of Sheffield': '175',
  'University of Birmingham': '175',
  'University of Bristol': '175',
  'University of York': '175',
  'Newcastle University': '225',
  'University of Nottingham': '225',
  'University of Leeds': '225',
  'Cardiff UniversityMore  United Kingdom': '275',
  'Durham University': '275',
  'Loughborough University': '275',
  'Royal Holloway University of London': '275',
  'University of Surrey': '275',
  'Brunel University London': '325',
  'Oxford Brookes University': '325',
  "Queen's University Belfast": '325',
  'University of St Andrews': '325',
  'City, University of London': '375',
  'Heriot-Watt University': '375',
  'The Open University': '375',
  'University of Aberdeen': '375',
  'University of Bath': '375',
  'University of Essex': '375',
  'University of Kent': '375',
  'University of Liverpool': '375',
  'University of Strathclyde': '375',
  'The University of Exeter': '425',
  'University of Leicester': '425',
  'Aston University': '475',
  'Coventry University': '475',
  'Cranfield University': '475',
  'University of Sussex': '475',
  'Goldsmiths, University of London': '525',
  'Swansea University': '525',
  'Kingston University, London': '575',
  'University of Portsmouth': '575',
  'University of Reading': '575',
  'Ulster University': '575'},
 'Switzerland': {'EPFL': '8',
  'ETH Zurich - Swiss Federal Institute of Technology': '9',
  'University of Zurich': '125',
  'University of Geneva': '225',
  'University of Bern': '375',
  'USI - Università della Svizzera italianaMore    Switzerland': '425',
  'University of Basel': '525'},
 'Canada': {'University of Toronto': '10',
  'University of Waterloo': '24',
  'University of British Columbia': '25',
  'McGill University': '75',
  'Université de MontréalMore  Canada': '75',
  'Simon Fraser University': '125',
  'University of Alberta': '125',
  "Queen's University at Kingston": '175',
  'Western University': '175',
  'McMaster University': '225',
  'University of Calgary': '225',
  'University of Ottawa': '225',
  'Université du Québec': '275',
  'University of Victoria': '275',
  'Concordia University': '325',
  'York University': '375',
  'Carleton University': '425',
  'Ryerson University': '425',
  'University of Manitoba': '425',
  'Dalhousie University': '475',
  'Université Laval': '525',
  'Université de Sherbrooke': '575'},
 'Singapore': {'National University of Singapore': '12',
  'Nanyang Technological University, Singapore': '16',
  'Singapore Management University': '175'},
 'China': {'Tsinghua University': '13',
  'Peking University': '19',
  'Shanghai Jiao Tong University': '34',
  'Fudan University': '75',
  'Nanjing University': '75',
  'University of Science and Technology of China': '75',
  'Zhejiang University': '75',
  'Sun Yat-sen University': '125',
  'Xi’an Jiaotong University': '125',
  'Harbin Institute of Technology': '175',
  'Huazhong University of Science and Technology': '175',
  'Wuhan University': '175',
  'Beijing Institute of Technology': '225',
  "Renmin (People's) University of China": '225',
  'Beihang University': '275',
  'Beijing Normal University': '325',
  'Beijing University of Posts and Telecommunications': '325',
  'Shandong University': '325',
  'University of Science and Technology Beijing': '325',
  'Beijing Jiaotong University': '375',
  'Jilin University': '375',
  'Shanghai University': '375',
  'Tongji University': '375',
  'University of Electronic Science and Technology of China': '425',
  'Xidian University': '425',
  'Beijing University of Technology': '475',
  'Nankai University': '475',
  'South China University of Technology': '475',
  'Southeast University': '475',
  'Dalian University of Technology': '525',
  'National University of Defense Technology': '575',
  'Northwestern Polytechnical University': '575',
  'Xiamen University': '575'},
 'Hong Kong': {'The Hong Kong University of Science and Technology': '26',
  'The Chinese University of Hong Kong': '30',
  'The University of Hong Kong': '38',
  'City University of Hong Kong': '75',
  'The Hong Kong Polytechnic University': '75',
  'Hong Kong Baptist University': '375'},
 'Japan': {'The University of Tokyo': '28',
  'Kyoto University': '75',
  'Tokyo Institute of Technology': '75',
  'Keio University': '125',
  'Osaka University': '125',
  'Kyushu University': '175',
  'Tohoku University': '175',
  'Waseda University': '175',
  'Nagoya University': '225',
  'Hokkaido University': '275',
  'University of Tsukuba': '325',
  'Japan Advanced Institute of Science and Technology': '425',
  'Kobe University': '475',
  'Ritsumeikan University': '475',
  'Hiroshima University': '575',
  'Nara Institute of Science and Technology': '575',
  'Osaka Prefecture University': '575'},
 'Australia': {'The University of Melbourne': '32',
  'The Australian National University': '41',
  'The University of Sydney': '42',
  'Monash University': '75',
  'The University of New South Wales': '75',
  'The University of Queensland': '75',
  'University of Technology Sydney': '75',
  'Queensland University of Technology': '125',
  'RMIT University': '125',
  'The University of Adelaide': '125',
  'The University of Western Australia': '175',
  'Deakin UniversityMore   Australia': '225',
  'Swinburne University of Technology': '225',
  'University of Wollongong': '225',
  'Macquarie University': '275',
  'The University of Newcastle, Australia': '275',
  'Curtin University': '325',
  'University of South Australia': '325',
  'Griffith University': '375',
  'Western Sydney University': '375',
  'La Trobe University': '475',
  'University of Canberra': '475',
  'Victoria University': '475'},
 'South Korea': {'KAIST - Korea Advanced Institute of Science & Technology': '36',
  'Seoul National University': '48',
  'Korea University': '75',
  'Pohang University of Science And Technology': '125',
  'Sungkyunkwan University': '125',
  'Yonsei University': '125',
  'Hanyang University': '175',
  'Kyung Hee University': '225',
  'Sogang University': '375',
  'Sejong University': '425',
  'Chung-Ang University': '475',
  'Konkuk University': '475',
  'Kyungpook National University': '475',
  'Ewha Womans University': '575',
  'Pusan National University': '575'},
 'Germany': {'Technical University of Munich': '36',
  'KIT, Karlsruhe Institute of Technology': '75',
  'Ludwig-Maximilians-Universität München': '75',
  'RWTH Aachen University': '75',
  'Technische Universität Berlin': '75',
  'Humboldt-Universität zu Berlin': '125',
  'Technical University of Darmstadt': '125',
  'Universität des Saarlandes': '125',
  'Freie Universitaet Berlin': '175',
  'Ruprecht-Karls-Universität Heidelberg': '175',
  'Technische Universität Dresden': '175',
  'Rheinische Friedrich-Wilhelms-Universität Bonn': '225',
  'Albert-Ludwigs-Universitaet Freiburg': '225',
  'Universität Stuttgart': '225',
  'Westfälische Wilhelms-Universität Münster': '275',
  'Eberhard Karls Universität Tübingen': '325',
  'Ruhr-Universität Bochum': '325',
  'TU Dortmund University': '325',
  'Universität Hamburg': '325',
  'University of Göttingen': '375',
  'Technische Universität Kaiserslautern': '375',
  'Friedrich-Alexander-Universität Erlangen-Nürnberg': '375',
  'Goethe-University Frankfurt am Main': '375',
  'Technische Universität Braunschweig': '425',
  'Universität Bremen': '425',
  'Universität Konstanz': '475',
  'Universität  Leipzig': '475',
  'Universität Duisburg-Essen': '525',
  'University Ulm': '525',
  'Leibniz University Hannover': '575',
  'Bielefeld University': '575'},
 'France': {'Université PSL': '39',
  'Ecole Polytechnique': '75',
  'Sorbonne University': '75',
  'CentraleSupélec': '125',
  'TELECOM Paris': '125',
  'Université Grenoble Alpes': '175',
  'Université Paris-Saclay': '225',
  'École Normale Supérieure de Lyon': '275',
  'IMT Atlantique': '275',
  'Université Diderot  Paris 7': '275',
  'Institut polytechnique de Grenoble - Grenoble Institute of Technology': '325',
  'Université de Montpellier': '325',
  'ENS Paris-Saclay': '375',
  'Institut National des Sciences Appliquées de Lyon': '375',
  'University of Bordeaux': '375',
  'Université de Lorraine': '425',
  'Université de Rennes 1': '425',
  'Université de Technologie de Compiègne': '425',
  'Université Paris 1 Panthéon-Sorbonne': '425',
  'Université Paul Sabatier Toulouse III': '425',
  'Université Claude Bernard Lyon 1': '475',
  'Université de Lille': '475',
  'Université Nice Sophia Antipolis': '475',
  'Aix-Marseille University': '525',
  'Université de Strasbourg': '525',
  'Ecole des Ponts ParisTech': '575',
  'EURECOM': '575',
  'Université Paris Descartes': '575',
  'Université Paris-Est Créteil Val de Marne': '575'},
 'Italy': {'Politecnico di Milano': '40',
  'Politecnico di Torino': '75',
  'Sapienza University of Rome': '75',
  'Alma Mater Studiorum - University of Bologna': '75',
  'University of Pisa': '75',
  'University of Milan': '125',
  'Università di Padova': '125',
  'University of Trento': '125',
  'University of Genoa': '275',
  'University of Naples - Federico II': '275',
  'University of Rome University of Rome "Tor Vergata"More Italy': '275',
  "Ca' Foscari University of Venice": '375',
  'University of Turin': '375',
  'University of Milano-Bicocca': '375',
  'Catania University': '425',
  'University of Florence': '425',
  'Università degli studi Roma Tre': '425',
  'University of Salerno': '475',
  'Verona University': '475',
  'Università degli Studi di Pavia': '525',
  'University of Modena and Reggio Emilia': '575'},
 'Sweden': {'KTH Royal Institute of Technology': '43',
  'Chalmers University of Technology': '125',
  'Uppsala University': '125',
  'Lund University': '175',
  'Linköping University': '225',
  'Stockholm University': '225',
  'University of Gothenburg': '425'},
 'Netherlands': {'University of Amsterdam': '75',
  'Delft University of Technology': '75',
  'Eindhoven University of Technology': '75',
  'Vrije Universiteit Amsterdam': '125',
  'University of Twente': '175',
  'Utrecht University': '225',
  'Leiden University': '275',
  'University of Groningen': '275',
  'Radboud University': '325',
  'Wageningen University & Research': '525',
  'Maastricht University': '575',
  'Tilburg University': '575'},
 'India': {'Indian Institute of Technology Bombay': '75',
  'Indian Institute of Technology Delhi': '75',
  'Indian Institute of Technology Kanpur': '125',
  'Indian Institute of Technology Kharagpur': '125',
  'Indian Institute of Technology Madras': '125',
  'Indian Institute of Science': '175',
  'Indian Institute of Technology Roorkee': '225',
  'Indian Institute of Technology Guwahati': '325',
  'Indian Statistical Institute': '325',
  'University of Delhi': '325',
  'International Institute of Information Technology - Hyderabad': '375',
  'Anna University': '425',
  'Jadavpur University': '425',
  'Birla Institute of Technology and Science, Pilani': '475',
  'Vellore Institute of Technology': '475',
  'Indian Institute of Information Technology, Allahabad': '575',
  'National Institute of Technology, Tiruchirappalli': '575'},
 'Belgium': {'KU Leuven': '75',
  'Université catholique de Louvain': '75',
  'Universite libre de Bruxelles': '225',
  'Ghent University': '225',
  'Vrije Universiteit Brussel': '275',
  'University of Antwerp': '425',
  'University of Mons': '425'},
 'Taiwan': {'National Chiao Tung University': '75',
  'National Tsing Hua University': '75',
  'National Cheng Kung University': '125',
  'National Taiwan University of Science and Technology': '175',
  'National Central University': '275',
  'National Chengchi University': '275',
  'National Sun Yat-sen University': '275',
  'National Taipei University of Technology': '375',
  'National Taiwan Normal University': '425',
  'National Chung Cheng University': '475',
  'National Chung Hsing University': '475',
  'Feng Chia University': '575',
  'Tamkang University': '575'},
 'Israel': {'Technion - Israel Institute of Technology': '75',
  'Tel Aviv University': '125',
  'The Hebrew University of Jerusalem': '175',
  'Weizmann Institute of Science': '275',
  'Ben-Gurion University of The Negev': '375',
  'Bar-Ilan University': '475'},
 'Austria': {'Vienna University of Technology': '75',
  'University of Vienna': '175',
  'Johannes Kepler University Linz': '275',
  'Graz University of Technology': '275',
  'Universität Innsbruck': '425',
  'WU': '425'},
 'New Zealand': {'The University of Auckland': '75',
  'Victoria University of Wellington': '175',
  'University of Canterbury': '275',
  'University of Otago': '275',
  'University of Waikato': '325',
  'Auckland University of Technology': '375',
  'Massey University': '375'},
 'Ireland': {'Trinity College Dublin, The University of Dublin': '75',
  'University College Dublin': '125',
  'University College Cork': '225',
  'Dublin City University': '275',
  'National University of Ireland Galway': '275',
  'University of Limerick': '325',
  'Maynooth University': '525',
  'Technological University of Dublin': '575'},
 'Chile': {'Universidad de Chile': '75',
  'Pontificia Universidad Católica de Chile': '125',
  'Universidad Técnica Federico Santa María': '325',
  'Universidad de Santiago de Chile': '425',
  'Universidad de Concepción': '525'},
 'Mexico': {'Universidad Nacional Autónoma de México': '75',
  'Tecnológico de Monterrey': '175',
  'Instituto Politécnico Nacional': '225',
  'Universidad de Guadalajara': '525',
  'Universidad Autónoma de Nuevo León': '575'},
 'Brazil': {'Universidade de São Paulo': '75',
  'Universidade Estadual de Campinas': '125',
  'Universidade Federal de Minas Gerais': '225',
  'Universidade Federal do Rio de Janeiro': '225',
  'Pontifícia Universidade Católica do Rio de Janeiro': '275',
  'Universidade Federal do Rio Grande Do Sul': '275',
  'UNESP': '325',
  'Universidade Federal de Pernambuco': '375',
  'Pontifícia Universidade Católica do Rio Grande do Sul': '525',
  'Universidade de Brasília': '525',
  'Universidade Federal de Santa Catarina': '525',
  'Universidade Federal do Paraná - UFPR': '525',
  'Universidade Federal de São Carlos': '575'},
 'Malaysia': {'Universiti Malaya': '75',
  'Universiti Putra Malaysia': '225',
  'Universiti Sains Malaysia': '225',
  'Universiti Teknologi Malaysia': '225',
  'Universiti Kebangsaan Malaysia': '275',
  'Universiti Teknologi PETRONAS': '375',
  'Multimedia University': '475',
  'Universiti Teknologi MARA - UiTM': '475',
  'International Islamic University Malaysia': '525',
  'Universiti Tunku Abdul Rahman': '575'},
 'Finland': {'Aalto University': '125',
  'University of Helsinki': '175',
  'University of Oulu': '325',
  'Tampere University of Technology': '425'},
 'Denmark': {'Aarhus University': '125',
  'University of Copenhagen': '125',
  'Aalborg University': '175',
  'Technical University of Denmark': '225',
  'University of Southern Denmark': '525'},
 'Russia': {'ITMO University': '125',
  'Saint Petersburg State University': '125',
  'Moscow Institute of Physics and Technology': '225',
  'HSE University': '225',
  'Bauman Moscow State Technical University': '325',
  'Novosibirsk State University': '325',
  'Peter the Great St. Petersburg Polytechnic University': '375',

In [15]:
f.close()

In [16]:
import json
# with open('rankings.json', 'w') as f:
#     json.dump(rankings_dict, f)
    
with open('rankings_dict.json', 'w') as f:
    json.dump(rankings_dict, f)